apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    app: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: manishjangra28/voting-example:result-app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200