apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: manishjangra28/voting-example:worker-app
        ports:
        - containerPort: 80

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: worker-app
# spec:
#   selector:
#     app: worker-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30100